Improve Travis configuration
This commit will put the quality assurance tools that Travis executes
into a different stage and also add support to PHP 7.3.

Signed-off-by: Henrique Moody <henriquemoody@gmail.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,34 +2,40 @@ sudo: false
 
 language: php
 
+php:
+  - 7.1
+  - 7.2
+  - 7.3
+  - nightly
+
 cache:
   directories:
     - $HOME/.composer/cache
 
-matrix:
-  include:
-    - php: 7.1
-      env: COMPOSER_ARGUMENTS="--prefer-lowest --prefer-stable"
-    - php: 7.1
-    - php: 7.2
-    - php: nightly
-  allow_failures:
-    - php: nightly
-  fast_finish: true
+before_install:
+  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
 
-before_script:
-  - composer update --prefer-dist ${COMPOSER_ARGUMENTS}
+install: travis_retry composer install
 
 script:
-  - vendor/bin/phpunit --colors --coverage-clover=test.clover
-  - |
-    if [[ "${TRAVIS_PHP_VERSION}" == "7.1" ]]; then
-      vendor/bin/docheader check src/ tests/
-    fi
+  - vendor/bin/phpunit --testsuite=unit
+  - vendor/bin/phpunit --testsuite=integration
 
-after_script:
-  - |
-    if [[ "${TRAVIS_PHP_VERSION}" == "7.1" ]]; then
-      wget https://scrutinizer-ci.com/ocular.phar
-      php ocular.phar code-coverage:upload --format=php-clover test.clover
-    fi
+jobs:
+  allow_failures:
+    - php: nightly
+
+  include:
+    - stage: Quality assurance
+      env: CODE_COVERAGE
+      before_script:
+        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
+        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
+      script: vendor/bin/phpunit --coverage-clover ./clover.xml
+      after_script:
+        - wget https://scrutinizer-ci.com/ocular.phar
+        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
+
+    - stage: Quality assurance
+      env: DOCHEADER
+      script: vendor/bin/docheader check src/ tests/
